### ISSUE TITLE
Can i get more details about your project?

### ISSUE THREAD

**Issue by codeomi** [pauljohnfigueroa/mern-fitness-app#1]
Can i get a breif description about your project.
Are you following any tutorial for making this project?

**Comment by pauljohnfigueroa** [comment]
> Can i get a breif description about your project. Are you following any tutorial for making this project?

Hi there, Thank you for asking, I am learning to connect ReactJS to NodeJs backend. Yes, I am following a tutorial for this specific project.

**Comment by codeomi** [comment]
That's really great! Can you drop the link of your tutorial?

**Comment by pauljohnfigueroa** [comment]
> That's really great! Can you drop the link of your tutorial?

Here's the tutorial from The Net Ninja. This is what I've been following. The explanations are very good and clear. 

MERN Stack Tutorial # 1
https://www.youtube.com/watch?v=98BzS5Oz5E4&list=PL4cUxeGkcC9iJ_KkrkBZWZRHVwnzLIoUE&index=1
MERN Authentication Tutorial #1 
https://www.youtube.com/watch?v=WsRBmwNkv3Q&list=PL4cUxeGkcC9g8OhpOZxNdhXggFz2lOuCT
